"""create-app — scaffold is the documentation (G7).

Generated app: require_cap=True, real secret, FileOnceBackend, one action, one morph.
Never ships require_cap=False.
"""

from __future__ import annotations

import secrets
from pathlib import Path

APP_PY = '''\
"""One-file CEK app — mint Cap → submit Intent → Result.ops."""

from __future__ import annotations

from pathlib import Path

from cek_host import FileOnceBackend, Host, doctor, explain
from cek_surface import Op, Surface

# Real secret. Never commit a demo secret. production() refuses the default.
SECRET = {secret!r}
ONCE = Path(__file__).with_name("once.json")


def main() -> None:
    host = Host.production(SECRET, FileOnceBackend(ONCE))
    print(doctor(host).to_text())

    s = Surface(kernel=host, carrier_kind="memory")

    @s.action("hello")
    def hello(ctx):
        name = str(ctx.args.get("name") or "world")
        return [Op.ui_morph("shell", {{"tag": "main", "text": f"hello, {{name}}"}})]

    cap = host.mint("hello", once=True, args={{"name": "cek"}}, seal_args=True)
    out = s.submit("hello", {{"name": "cek"}}, cap=cap, drain_async=False)
    result = out["result"]
    print("kind:", result["kind"], "ops:", len(result.get("ops") or []))
    if result["kind"] != "ok":
        print(explain(result.get("error")).render())
        raise SystemExit(1)

    again = s.submit("hello", {{"name": "cek"}}, cap=cap, drain_async=False)
    assert again["result"]["kind"] == "authority_refusal"
    assert again["result"]["ops"] == []
    print("once replay refused — ops:[]")
    s.close()


if __name__ == "__main__":
    main()
'''

README = """\
# {name}

Generated by `python -m cek_host create-app`.

```bash
pip install -e /path/to/cek-python/cek-host -e /path/to/cek-python/cek-surface
python app.py
python -m cek_host doctor --fail
```

`Host.production` + `FileOnceBackend`. `require_cap=True`. Secret is 32 random bytes.
Once-replay must print `ops:[]`.

Read first: https://github.com/bitplorer/cek-python/blob/main/START.md
"""


def create_app(dest: str | Path) -> Path:
    root = Path(dest)
    root.mkdir(parents=True, exist_ok=True)
    secret = secrets.token_bytes(32)
    (root / "app.py").write_text(APP_PY.format(secret=secret), encoding="utf-8")
    (root / "README.md").write_text(README.format(name=root.name), encoding="utf-8")
    return root
